version: '3'
services:
    nginx:
      build: 
        context: requirements/nginx
        dockerfile: Dockerfile
      container_name: nginx
      volumes:
      - nginx:/var/www/html/
      image: nginx
      ports:
      - "8000:8000"
      restart: always
volumes:
        nginx:
                driver: local
                driver_opts:
                        type: none
                        o: bind
                        device: /home/ubuntu/data/nginx

    wordpress:
      build:
        context: requirements/wordpress
        dockerfile: Dockerfile
      container_name: wordpress
      volumes:
      - wordpress:/var/www/html/
      image: wordpress
      restart: always
volumes:
        wordpress:
                driver: local
                driver_opts:
                        type: none
                        o: bind
                        device: /home/ubuntu/data/nginx

networks:
        network:
                name: inception-network
                driver: bridge
